name       : gpsbabel
version    : 1.5.4
release    : 1
source     :
    - https://github.com/gpsbabel/gpsbabel/archive/gpsbabel_1_5_4.tar.gz : 8cd740db0b92610abff71e942e8a987df58cd6ca5f25cca86e15f2b00e190704
license    : GPL-2.0
component  : system.utils
summary    : Free software for GPS data conversion and transfer
description: |
    GPSBabel converts waypoints, tracks, and routes between popular GPS receivers such as Garmin or Magellan and mapping programs like Google Earth or Basecamp. Literally hundreds of GPS receivers and programs are supported. It also has powerful manipulation tools for such data. such as filtering duplicates points or simplifying tracks. It has been downloaded and used tens of millions of times since it was first created in 2001, so it's stable and trusted.
    
    By flattening the Tower of Babel that the authors of various programs for manipulating GPS data have imposed upon us, GPSBabel returns to us the ability to freely move our own waypoint data between the programs and hardware we choose to use.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gl)
    - pkgconfig(libusb)
    - docbook-xml
setup      : |
    %patch -p1 < $pkgfiles/build-fix.patch
    %patch -p1 < $pkgfiles/drop-map.patch

    sed -i 's|langPath_ = QApplication::applicationDirPath();|langPath_ = "/usr/share/gpsbabel";|' gui/mainwindow.cc
    sed -i 's|baseFile =  QApplication::applicationDirPath() |baseFile = "/usr/share/gpsbabel" |' gui/map.cc
    %configure --prefix=/usr

    # GUI
    pushd gui
    %qmake
    lrelease *.ts
    popd
build      : |
    %make

    # GUI
    pushd gui
    %make
    popd
install    : |
    %make_install

    # GUI
    install -Dm 0755 gui/objects/gpsbabelfe-bin $installdir/usr/bin/gpsbabelfe-bin
    install -Dm 0644 gui/images/appicon.png $installdir/usr/share/pixmaps/gpsbabel.png
    install -Dm 0644 gui/gpsbabel.desktop $installdir/usr/share/applications/gpsbabel.desktop
    install -Dm 0644 gui/gmapbase.html $installdir/usr/share/gpsbabel/gmapbase.html
    install -dm 0755 $installdir/usr/share/gpsbabel/translations/
    install -Dm 0644 gui/*.qm $installdir/usr/share/gpsbabel/translations/
    # devel
    install -dm 0755 $installdir/usr/include/gpsbabel/
    install -Dm 0644 *.h $installdir/usr/include/gpsbabel/
